import Fastify, { FastifyInstance } from "fastify";
import cookie from "@fastify/cookie";
import formbody from "@fastify/formbody";
import { config } from "../config";
import { registerApiRoutes } from "./routes/api";
import { registerSiteRoutes } from "./routes/sites";
import { registerAuthRoutes } from "./routes/auth";
import fs from "node:fs";
import path from "node:path";

// Path to the built SPA (generated by `vite build` → dist/client/)
const SPA_DIR = path.join(__dirname, "..", "..", "dist", "client");

export async function buildApp(): Promise<FastifyInstance> {
  if (!config.dashboardPassword) throw new Error("Missing required env var: DASHBOARD_PASSWORD");
  if (!config.sessionSecret) throw new Error("Missing required env var: SESSION_SECRET");

  const app = Fastify({ logger: true, trustProxy: true });

  await app.register(cookie, { secret: config.sessionSecret });
  await app.register(formbody);

  // API routes (JSON)
  await registerAuthRoutes(app);
  await registerApiRoutes(app);
  await registerSiteRoutes(app);

  // Static assets (favicon, etc.)
  app.register(require("@fastify/static").default, {
    root: path.join(SPA_DIR, "assets"),
    prefix: "/assets/",
  });
  app.get("/favicon.svg", async () => {
    const favPath = path.join(__dirname, "..", "..", "public", "favicon.svg");
    return fs.readFileSync(favPath);
  });

  // SPA fallback — serve index.html for all non-API routes
  const indexPath = path.join(SPA_DIR, "index.html");
  if (!fs.existsSync(indexPath)) {
    console.warn("SPA not built. Run `npx vite build` first.");
  }

  app.setNotFoundHandler(async (request, reply) => {
    if (request.url.startsWith("/api/") || request.url === "/health") {
      return reply.code(404).send({ error: "not found" });
    }
    try {
      const html = fs.readFileSync(indexPath, "utf-8");
      return reply.type("text/html").send(html);
    } catch {
      return reply.code(500).send("SPA not built. Run `npx vite build` first.");
    }
  });

  return app;
}
